### ISSUE TITLE
Warning message in the latest version v22.12.0

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-teku-prater#102]
**Describe the bug**

Install version v22.12.0 and check the validator logs. The performance of the validator is not affected but a warning appears in the logs of the validator.

**To Reproduce**

**Expected behaviour**

It should not appears this kind of warning.

**Additional context**
`2022-12-15 07:08:01.889 WARN  - handleException /eth/v1/remotekeys org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI`

**Comment by dsimog01** [comment]
I am following this Teku tutorial to fix the issue: https://docs.teku.consensys.net/en/stable/Tutorials/Configure-External-Signer-TLS/

**Comment by pablomendezroyo** [comment]
Can this be closed ?

**Comment by dsimog01** [comment]
Yes!
