### ISSUE TITLE
Lock `public_keys.txt` file to improve security

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-Teku-Prater#19]
## Context
The `public_keys.txt` files contains the public keys used to start the teku binary for the validator flags. This file must not change unless the public keys exposed by the web3signer API are different, then it should be edited and the process will restart

## To do
- Find a way to lock the file `public_keys.txt` and unlock it when required to avoid possible bugs.(`chattrd` cannot be used in docker containers)
- Consider using docker volumes stuff to provide read-only access

**Comment by 3alpha** [comment]
Does `flock` work?

**Comment by pablomendezroyo** [comment]
I did not tried, but I would say this stuff could be tricky to implement in a docker container

**Comment by pablomendezroyo** [comment]
would be great to find a way to be sure this file will not be modified. Is it possible to provide a password to be able to modify a file or something similar?

**Comment by pablomendezroyo** [comment]
Ensure this file will not be modified by nothing else but the `entrypoint.sh` and the `get_keys.sh` cronjob

**Comment by 3alpha** [comment]
Are you worried about malicious actor or some other process?

- If it is about malicious actor, I don't think that is something we can cover. If somebody has gained container level access, then it is game over, changing permissions won't fix anything
- If it is about some other process, then we have bigger issue and problem has to be fixed at source

**Comment by pablomendezroyo** [comment]
hmm okey, agree. Then please, review in deep the code specially from the cronjob `get_keys.sh` script and found possible bugs. Im afraid of infinite loops and stuff like that. Also, did you test it?

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodePackage-Teku-Prater/issues/25
