### ISSUE TITLE
Track Teku

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-teku-prater#55]
Track the most important features in the road to Eth2 multiclient in DAppNode of the Teku client.

- [x] Implement web3signer support
- [x] Immplement validator remote keymanager API: :rocket: https://github.com/dappnode/DAppNodePackage-Teku-Prater/pull/56
- [x] Implement fee recipient: https://github.com/dappnode/DAppNodePackage-teku-prater/pull/64
- [x] Run as separated services
- [x] Checkpoint sync 
- [x] DAppNode package for Gnosis chain
- [x] DAppNode package for mainnet
- [x] Implement JWT

**Comment by dsimog01** [comment]
This has already been solved
