### ISSUE TITLE
Mismatch between URL link and Version under the "Version" information in the DAppStore Installer page

### ISSUE THREAD

**Issue by sushilman** [dappnode/DAppNodePackage-Teku-Prater#58]
**Describe the bug**

Mismatch between URL link and Version under the "Version" information in the DAppStore Installer page.

As you can see in the screenshot, the version link for the DAppNode package points to the url of the upstream package but with the version of the DAppNode package

**To Reproduce**
Just visit the http://dappnode.local/#/installer/teku-prater.dnp.dappnode.eth and hover / click the version link

**Expected behavior**
As in other DAppNode packages, the link should point to the DAppNode github repo instead of the upstream repo

**Screenshots**

![dappnode_teku](https://user-images.githubusercontent.com/173456/166909898-14ae37bb-5fe8-4b84-8b6f-4d0311bba147.png)

**DAppNode version:**

- Package version: v0.1.2 
- OS: 
- Browser: Brave

**Comment by pablomendezroyo** [comment]
Most of the times issues come from the upstream github project (Teku in this case) and not from our repository, thats why we redirect users to the upstream and not to ours

**Comment by sushilman** [comment]
Right that makes sense. 

However, the link is still incorrect because it takes you to [https://github.com/ConsenSys/teku/releases/v0.1.2](https://github.com/ConsenSys/teku/releases/v0.1.2) which does not exist, instead of [https://github.com/ConsenSys/teku/releases/22.3.2](https://github.com/ConsenSys/teku/releases/22.3.2)
