### ISSUE TITLE
Test teku + web3signer in network prater

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-teku-prater#61]
**Test instructions**

You must have at least 2 Prater validators.

Install the [web3signer prater](https://github.com/dappnode/DAppNodePackage-web3signer-prater) and the client [Teku](https://github.com/dappnode/DAppNodePackage-teku-prater). You must get the hash from the Github latest release "dot".

In the client use the checkpoint sync feature to be able to start validating in minutes.

The web3signer will listen only to one client, you must select the client Teku at config.

For a deeper test, you may find it useful to check out the grafana dashboards from the client, web3signer, and docker host.

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

**Testers**
- @pablomendezroyo :heavy_check_mark: 
- @3alpha 
- @tropicar :heavy_check_mark: 
- @mgarciate :heavy_check_mark:

**Comment by Pol-Lanski** [comment]
Blocked by core version 0.2.50 https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.50
In order to test with the latest web3signer version, the CORE needs to be updated.

**Comment by pablomendezroyo** [comment]
worked on my side :heavy_check_mark:

**Comment by tropicar** [comment]
Works from side :heavy_check_mark:
